[colors.primary]
background = '#0f1416'
foreground = '#dee3e6'
 
[colors.cursor]
text = '#dee3e6'
cursor = '#bfc8cc' 
 
[colors.vi_mode_cursor]
text = '#0f1416'
cursor = '#88d0ec' 
 
[colors.search.matches]
foreground = '#40484c' 
background = '#c3c3eb' 
 
[colors.search.focused_match]
foreground = '#40484c' 
background = '#88d0ec' 
 
[colors.footer_bar]
foreground = '#40484c' 
background = '#dee3e6' 
 
[colors.hints.start]
foreground = '#40484c' 
background = '#b3cad5' 
 
[colors.hints.end]
foreground = '#40484c' 
background = '#b3cad5' 
 
[colors.selection]
text = '#0f1416'
background = '#88d0ec'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#88d0ec' 
yellow = '#09677f' 
blue = '#88d0ec' 
magenta = '#c3c3eb' 
cyan = '#b3cad5' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 
