[colors.primary]
background = '#181115'
foreground = '#eddfe4'
 
[colors.cursor]
text = '#eddfe4'
cursor = '#d3c2c9' 
 
[colors.vi_mode_cursor]
text = '#181115'
cursor = '#fab1da' 
 
[colors.search.matches]
foreground = '#4f4349' 
background = '#f4ba9e' 
 
[colors.search.focused_match]
foreground = '#4f4349' 
background = '#fab1da' 
 
[colors.footer_bar]
foreground = '#4f4349' 
background = '#eddfe4' 
 
[colors.hints.start]
foreground = '#4f4349' 
background = '#debece' 
 
[colors.hints.end]
foreground = '#4f4349' 
background = '#debece' 
 
[colors.selection]
text = '#181115'
background = '#fab1da'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#fab1da' 
yellow = '#864b6f' 
blue = '#fab1da' 
magenta = '#f4ba9e' 
cyan = '#debece' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 
